# **Imports**

In [ ]:

from earthscape.utils.constants import VERSION, ASSETS_DIR, MODEL_DIR
import os
import glob
import numpy as np
import pandas as pd
from scipy.stats import t
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter
from matplotlib.patches import Patch
import seaborn as sns

# **Setup**

In [2]:
#############################################
# Setup input and output directories & paths
#############################################

# directory of experiments
exp_dir = r'../experiments/baselines/segmentation'

# single modality experiments...
single_root = os.path.join(exp_dir, 'single')
single_dirs = glob.glob(f"{single_root}/*")

# multi-scale modality experiments...
ms_root = os.path.join(exp_dir, 'multiscale')
ms_dirs = glob.glob(f"{ms_root}/*")

# multimodal experiments modalities...
mm_root = os.path.join(exp_dir, 'multimodal')
mm_dirs = glob.glob(f"{mm_root}/*")

# output directory for visualizations...
assets_dir = os.path.join(exp_dir.replace(MODEL_DIR, ASSETS_DIR))
if not os.path.isdir(assets_dir):
    os.makedirs(assets_dir)

# **Data Cleaning & Performance Compilations**

## *Clean per-Class Metrics*

In [ ]:
##################################################
#

## *Single Modality Experiments*

In [ ]:
##################################################
# Compile Global Performance Metrics - Single
##################################################

# # output path for global summary
# output_path = os.path.join(assets_dir, 'single_global.csv')


##### compile global in- & cross-domain data...
# initialize df
df = pd.DataFrame(columns=['model', 'input'])

# collect global data from all experiments...
for idx, d in enumerate(single_dirs):
    
    # skip any files in root directory...
    if os.path.isfile(d):
        continue
    
    # metadata of model name & modality input...
    meta = os.path.basename(d)
    meta = meta.split('_')
    model_name = meta[0]
    modalities = meta[1]

    # in-domain...
    id_global_path = os.path.join(d, 'id_global.csv')
    id = pd.read_csv(id_global_path)
    id.columns = [col +' (id)' for col in id.columns]
    
    # cross-domain...
    cd_global_path = os.path.join(d, 'cd_global.csv')
    cd = pd.read_csv(cd_global_path)
    cd.columns = [col +' (cd)' for col in cd.columns]

    # merge datasets...
    df.loc[idx, 'model'] = model_name
    df.loc[idx, 'input'] = modalities
    df.loc[idx, id.columns] = id.values
    df.loc[idx, cd.columns] = cd.values

# save & display...
# df.to_csv(output_path, index=False)
# df.sort_values('macro_map (id)', ascending=False).head(10)

In [23]:
df = pd.read_csv(r"..\experiments\baselines\segmentation\single\deeplabv3p-resnet50_dem_20260326_040730\id_overall_class.csv")

df.head(10)

,class,iou,dice,precision,recall,hd,hd95,gt_support,pred_support,gt_class_support,pred_class_support,tp,fp,fn,tn
0,Qaf,0.000000,0.000000,NaN,0.000000,NaN,NaN,10183,0,10,0,0,0,10183,100653113
1,Qal,0.602991,0.752332,0.793541,0.715192,102.194606,89.871501,8361713,7536136,947,928,5980234,1555902,2381479,90745681
2,Qat,0.167080,0.286322,0.350267,0.242120,138.630799,128.979286,388848,268789,61,60,94148,174641,294700,100099807
3,Qc,0.780963,0.877012,0.852419,0.903067,81.528120,65.504072,16237424,17202215,748,807,14663487,2538728,1573937,81887144
4,Qca,0.436787,0.608005,0.677539,0.551415,111.000578,96.168558,7202703,5861922,431,419,3971679,1890243,3231024,91570350
5,Qr,0.832185,0.908407,0.881087,0.937475,76.671479,57.395806,62099929,66074243,1433,1503,58217150,7857093,3882779,30706274
6,af1,0.431438,0.602804,0.816906,0.477624,118.314330,107.402893,6362496,3719991,570,359,3038882,681109,3323614,93619691

In [ ]:
"""

CLEAN UP id/cd_overall_class.csv

"""

In [25]:
from earthscape.evaluation import overall_metrics_seg, overall_class_metrics_seg

In [26]:
for d in single_dirs:

    df_class = pd.read_csv(os.path.join(d, 'id_img_class.csv'))

    file = os.path.join(d, 'id_overall_class.csv')
    # df = pd.read_csv(file)

    # df = overall_metrics_seg(df_class)

    df = overall_class_metrics_seg(df_class)

    # df.to_csv(file, index=False)

    break

df.head(10)

,class,micro_iou,micro_dice,micro_precision,micro_recall,mean_hd,mean_hd95,gt_support,pred_support,gt_class_support,pred_class_support,tp,fp,fn,tn
0,Qaf,0.000000,0.000000,NaN,0.000000,NaN,NaN,10183,0,10,0,0,0,10183,100653113
1,Qal,0.602991,0.752332,0.793541,0.715192,102.194606,89.871501,8361713,7536136,947,928,5980234,1555902,2381479,90745681
2,Qat,0.167080,0.286322,0.350267,0.242120,138.630799,128.979286,388848,268789,61,60,94148,174641,294700,100099807
3,Qc,0.780963,0.877012,0.852419,0.903067,81.528120,65.504072,16237424,17202215,748,807,14663487,2538728,1573937,81887144
4,Qca,0.436787,0.608005,0.677539,0.551415,111.000578,96.168558,7202703,5861922,431,419,3971679,1890243,3231024,91570350
5,Qr,0.832185,0.908407,0.881087,0.937475,76.671479,57.395806,62099929,66074243,1433,1503,58217150,7857093,3882779,30706274
6,af1,0.431438,0.602804,0.816906,0.477624,118.314330,107.402893,6362496,3719991,570,359,3038882,681109,3323614,93619691

In [107]:
df_class.head(14)

,patch_id,class,gt_support,pred_support,tp,fp,fn,tn,iou,dice,precision,recall,hd,hd95,gt_present,pred_present
0,256_50_1781,af1,0,0,0,0,0,65536,NaN,NaN,NaN,NaN,NaN,NaN,False,False
1,256_50_1781,Qal,11901,11688,11377,311,524,53324,0.931625,0.964602,0.973392,0.955970,14.000000,4.123106,True,True
2,256_50_1781,Qaf,0,0,0,0,0,65536,NaN,NaN,NaN,NaN,NaN,NaN,False,False
3,256_50_1781,Qat,0,0,0,0,0,65536,NaN,NaN,NaN,NaN,NaN,NaN,False,False
4,256_50_1781,Qc,32368,31753,30013,1740,2355,31428,0.879940,0.936136,0.945202,0.927243,46.690472,16.278820,True,True
5,256_50_1781,Qca,0,0,0,0,0,65536,NaN,NaN,NaN,NaN,NaN,NaN,False,False
6,256_50_1781,Qr,21267,22095,20051,2044,1216,42225,0.860152,0.924819,0.907490,0.942822,19.104973,12.041595,True,True
7,256_50_14066,af1,20,0,0,0,20,65516,0.000000,0.000000,0.000000,0.000000,NaN,NaN,True,False
8,256_50_14066,Qal,60373,63586,59965,3621,408,1542,0.937041,0.967497,0.943053,0.993242,62.128899,39.762718,True,True
9,256_50_14066,Qaf,0,0,0,0,0,65536,NaN,NaN,NaN,NaN,NaN,NaN,False,False
10,256_50_14066,Qat,0,0,0,0,0,65536,NaN,NaN,NaN,NaN,NaN,NaN,False,False
11,256_50_14066,Qc,0,0,0,0,0,65536,NaN,NaN,NaN,NaN,NaN,NaN,False,False
12,256_50_14066,Qca,0,0,0,0,0,65536,NaN,NaN,NaN,NaN,NaN,NaN,False,False
13,256_50_14066,Qr,5143,1950,1542,408,3601,59985,0.277788,0.434795,0.790769,0.299825,42.638012,33.428650,True,True

In [102]:
df_class[['iou', 'dice', 'precision', 'recall', 'hd95']].mean(axis=0)

iou           0.456716
dice          0.520123
precision     0.578694
recall        0.537224
hd95         74.148849
dtype: float64