# **Imports**

In [83]:

import os
import glob

import numpy as np
import pandas as pd

import torch
from earthscape.loaders import ESDataset_Classification

from earthscape.evaluation import get_global_metrics, get_class_metrics

# **Setup**

In [71]:

# directory path to experiments...
# single_dir = r'../experiments/classification/baselines/single'
# ms_dir = r'../experiments/classification/baselines/multiscale'
# mm_dir = r'../experiments/classification/baselines/multimodal'

# exp_dirs = glob.glob(r'../experiments/classification/baselines/**/*')

exp_dirs = [d for d in glob.glob(r'../experiments/classification/baselines/**/*') if 'single' not in d]


# dictionary of experiments & directory paths...
experiments = {}
for d in exp_dirs:
    basename_list = os.path.basename(d).split('_')[:-2]
    model = basename_list.pop(0)
    exp_type = os.path.basename(os.path.dirname(d))
    in_features = '_'.join(basename_list)

    if model not in experiments.keys():
        experiments[model] = {}

    if exp_type not in experiments[model].keys():
        experiments[model][exp_type] = {}

    experiments[model][exp_type][in_features] = d

experiments

{'resnet18': {'multimodal': {'dem_aerial': '../experiments/classification/baselines\\multimodal\\resnet18_dem_aerial_20260304_084802',
   'dem_ep': '../experiments/classification/baselines\\multimodal\\resnet18_dem_ep_20260304_092236',
   'dem_nhd': '../experiments/classification/baselines\\multimodal\\resnet18_dem_nhd_20260304_090434',
   'dem_osm': '../experiments/classification/baselines\\multimodal\\resnet18_dem_osm_20260304_091341',
   'dem_plc': '../experiments/classification/baselines\\multimodal\\resnet18_dem_plc_20260304_094147',
   'dem_prc': '../experiments/classification/baselines\\multimodal\\resnet18_dem_prc_20260304_100552',
   'dem_rgb': '../experiments/classification/baselines\\multimodal\\resnet18_dem_rgb_20260304_083455',
   'dem_sds': '../experiments/classification/baselines\\multimodal\\resnet18_dem_sds_20260304_105104',
   'dem_s': '../experiments/classification/baselines\\multimodal\\resnet18_dem_s_20260304_102701'},
  'multiscale': {'ep': '../experiments/classification/baselines\\multiscale\\resnet18_ep_20260303_162320',
   'plc': '../experiments/classification/baselines\\multiscale\\resnet18_plc_20260303_164007',
   'prc': '../experiments/classification/baselines\\multiscale\\resnet18_prc_20260303_165924',
   'sds': '../experiments/classification/baselines\\multiscale\\resnet18_sds_20260303_173935',
   's': '../experiments/classification/baselines\\multiscale\\resnet18_s_20260303_171957'}},
 'resnet50': {'multimodal': {'dem_aerial': '../experiments/classification/baselines\\multimodal\\resnet50_dem_aerial_20260304_112700',
   'dem_ep': '../experiments/classification/baselines\\multimodal\\resnet50_dem_ep_20260304_120648',
   'dem_nhd': '../experiments/classification/baselines\\multimodal\\resnet50_dem_nhd_20260304_114158',
   'dem_osm': '../experiments/classification/baselines\\multimodal\\resnet50_dem_osm_20260304_115527',
   'dem_plc': '../experiments/classification/baselines\\multimodal\\resnet50_dem_plc_20260304_122812',
   'dem_prc': '../experiments/classification/baselines\\multimodal\\resnet50_dem_prc_20260304_124728',
   'dem_rgb': '../experiments/classification/baselines\\multimodal\\resnet50_dem_rgb_20260304_111451',
   'dem_sds': '../experiments/classification/baselines\\multimodal\\resnet50_dem_sds_20260304_133245',
   'dem_s': '../experiments/classification/baselines\\multimodal\\resnet50_dem_s_20260304_130827'},
  'multiscale': {'ep': '../experiments/classification/baselines\\multiscale\\resnet50_ep_20260303_180638',
   'plc': '../experiments/classification/baselines\\multiscale\\resnet50_plc_20260303_182538',
   'prc': '../experiments/classification/baselines\\multiscale\\resnet50_prc_20260303_184237',
   'sds': '../experiments/classification/baselines\\multiscale\\resnet50_sds_20260303_192201',
   's': '../experiments/classification/baselines\\multiscale\\resnet50_s_20260303_190120'}},
 'swin': {'multimodal': {'dem_aerial': '../experiments/classification/baselines\\multimodal\\swin_dem_aerial_20260305_145325',
   'dem_ep': '../experiments/classification/baselines\\multimodal\\swin_dem_ep_20260305_162529',
   'dem_nhd': '../experiments/classification/baselines\\multimodal\\swin_dem_nhd_20260305_153501',
   'dem_osm': '../experiments/classification/baselines\\multimodal\\swin_dem_osm_20260305_155734',
   'dem_plc': '../experiments/classification/baselines\\multimodal\\swin_dem_plc_20260305_170441',
   'dem_prc': '../experiments/classification/baselines\\multimodal\\swin_dem_prc_20260305_173340',
   'dem_rgb': '../experiments/classification/baselines\\multimodal\\swin_dem_rgb_20260305_141112',
   'dem_sds': '../experiments/classification/baselines\\multimodal\\swin_dem_sds_20260305_184629',
   'dem_s': '../experiments/classification/baselines\\multimodal\\swin_dem_s_20260305_181327'},
  'multiscale': {'ep': '../experiments/classification/baselines\\multiscale\\swin_ep_20260305_105458',
   'plc': '../experiments/classification/baselines\\multiscale\\swin_plc_20260305_112159',
   'prc': '../experiments/classification/baselines\\multiscale\\swin_prc_20260305_120557',
   'sds': '../experiments/classification/baselines\\multiscale\\swin_sds_20260305_125318',
   's': '../experiments/classification/baselines\\multiscale\\swin_s_20260305_123016'}},
 'vit': {'multimodal': {'dem_aerial': '../experiments/classification/baselines\\multimodal\\vit_dem_aerial_20260304_143746',
   'dem_ep': '../experiments/classification/baselines\\multimodal\\vit_dem_ep_20260304_165237',
   'dem_nhd': '../experiments/classification/baselines\\multimodal\\vit_dem_nhd_20260304_154110',
   'dem_osm': '../experiments/classification/baselines\\multimodal\\vit_dem_osm_20260304_161549',
   'dem_plc': '../experiments/classification/baselines\\multimodal\\vit_dem_plc_20260304_174225',
   'dem_prc': '../experiments/classification/baselines\\multimodal\\vit_dem_prc_20260304_183949',
   'dem_rgb': '../experiments/classification/baselines\\multimodal\\vit_dem_rgb_20260304_140902',
   'dem_sds': '../experiments/classification/baselines\\multimodal\\vit_dem_sds_20260304_201404',
   'dem_s': '../experiments/classification/baselines\\multimodal\\vit_dem_s_20260304_193712'},
  'multiscale': {'ep': '../experiments/classification/baselines\\multiscale\\vit_ep_20260304_045602',
   'plc': '../experiments/classification/baselines\\multiscale\\vit_plc_20260304_053151',
   'prc': '../experiments/classification/baselines\\multiscale\\vit_prc_20260304_060050',
   'sds': '../experiments/classification/baselines\\multiscale\\vit_sds_20260304_073446',
   's': '../experiments/classification/baselines\\multiscale\\vit_s_20260304_063932'}}}

In [ ]:
#############################################
# In-Domain Performance Metrics for Models
#############################################


df = pd.DataFrame()

for model in experiments.keys():

    for exp in experiments[model].keys():

        for input, dir_path in experiments[model][exp].items():
            
            idx = len(df)

            in_path = glob.glob(f"{dir_path}/*predictions_id.csv")[0]
            
            probs = pd.read_csv(in_path)

            df.loc[idx, 'precision'] = 






            
            df.loc[idx, 'model'] = model
            df.loc[idx, 'exp_type'] = exp
            df.loc[idx, 'input'] = input
            # df.loc[idx, data.columns] = data.values
            
            

            break
        break
    break

df.head()

      model    exp_type       input
0  resnet18  multimodal  dem_aerial

In [ ]:
probs

,patch_id,af1,Qal,Qaf,Qat,Qc,Qca,Qr
0,256_50_1781,0.077145,0.988782,0.063417,0.070356,0.999648,0.825222,0.894861
1,256_50_14066,0.961581,0.991647,0.000384,0.005141,0.092756,0.094904,0.836293
2,256_50_14962,0.068390,0.988546,0.014829,0.444935,0.539282,0.052691,0.971435
3,256_50_11340,0.668578,0.381688,0.000119,0.000172,0.003763,0.004009,0.993290
4,256_50_6211,0.176706,0.134520,0.005374,0.021835,0.937162,0.417342,0.980976
...,...,...,...,...,...,...,...,...
1531,256_50_16803,0.037648,0.685496,0.002157,0.005736,0.041437,0.010626,0.999641
1532,256_50_3990,0.260314,0.514605,0.001606,0.007410,0.944598,0.132401,0.998794
1533,256_50_17052,0.851062,0.429335,0.000525,0.001376,0.009936,0.010386,0.991040
1534,256_50_3622,0.076662,0.115253,0.000140,0.002325,0.034719,0.004508,0.999963
1535,256_50_11177,0.760023,0.948736,0.006296,0.067298,0.993253,0.759825,0.975501

In [116]:
paths = glob.glob(r'../experiments/**/*predictions*.csv', recursive=True)

In [118]:
paths[0]

'../experiments\\classification\\baselines\\multimodal\\resnet18_dem_aerial_20260304_084802\\predictions_cd.csv'

In [119]:

for p in paths[1:]:
    df = pd.read_csv(p)
    df.drop(columns=df.columns[0], inplace=True)
    df.to_csv(p, index=False)